version: "3.8"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: cookies
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: adm123
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo:/data/db
      - ./init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js